M48
; DRILL file {KiCad (6.0.5)} date Sat Jun  4 22:54:36 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-04T22:54:36-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.2500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.4331
%
G90
G05
T2
X4.2Y-1.875
X4.6Y-6.875
T3
X4.4Y-6.15
T4
X4.4Y-2.4
T1
G00X4.6362Y-6.1795
M15
G01X4.6362Y-6.1205
M16
G05
T0
M30
